[package]
name = "preview"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.11.3", features = [ "bevy_render", "bevy_winit" ] }
bevy_egui = "0.22.0"
